stages:
  - mirror

mirror:
  stage: mirror
  script:
    - git push --mirror https://kontopoulosdm:$GITHUB_TOKEN@github.com/kontopoulosdm/hubs
  only:
    - master # Trigger only for changes in the master branch

