let bit = 0;
const nextBit = () => 1 << bit++;
const CL = {
  ALL: -1,
  NONE: 0,
  INTERACTABLES: nextBit(),
  ENVIRONMENT: nextBit(),
  AVATAR: nextBit(),
  HANDS: nextBit(),
  MEDIA_FRAMES: nextBit()
};

CL.DEFAULT_INTERACTABLE = CL.INTERACTABLES | CL.ENVIRONMENT | CL.AVATAR | CL.HANDS | CL.MEDIA_FRAMES;
CL.UNOWNED_INTERACTABLE = CL.INTERACTABLES | CL.HANDS;
CL.DEFAULT_SPAWNER = CL.INTERACTABLES | CL.HANDS;

module.exports = {
  COLLISION_LAYERS: CL
};
